apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-trioapp-prod-asia
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: demo-prod-asia
  source:
    path: demo-applications/trioapp-prod-asia
    repoURL: https://github.com/codefresh-sandbox/codefresh-quickstart-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
